
python3 scripts/train_tc.py --env OpenDoorLoc --model bc10 --demos /home/ethantqiu/Thought-Cloning/demos/odl10 --memory-dim=1024 --recurrence=64 --batch-size=256 --instr-arch=attgru --instr-dim=256 --val-interval 2 --log-interval 2 --lr 5e-4 --epochs 20 --epoch-length 8192 --seed 0 --val-seed 2023  --sg-coef 2 --stop-tf 5 --tb --episodes 4096 --device 1 --val-episodes 32 --expr-group-name LOG_odl --wandb-id bc10 
cp -r LOG_odl/models/bc10 LOG_odl/models/asaptune10
cp -r LOG_odl/models/bc10 LOG_odl/models/qatune10
python3 scripts/train_rl.py --env OpenDoorLoc --model asaptune10 --demos /home/ethantqiu/Thought-Cloning/demos/odl10 --memory-dim=1024 --recurrence=3 --batch-size=256 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 1e-4 --epochs 10 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_odl --device 1 --wandb-id asaptune10 --target-update-period 128
python3 scripts/train_rl.py --env OpenDoorLoc --model qatune10 --demos /home/ethantqiu/Thought-Cloning/demos/odl10 --memory-dim=1024 --recurrence=3 --batch-size=256 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 1e-4 --epochs 10 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_odl --device 1 --wandb-id qa10 --target-update-period 128 --lower-only
cp -r LOG_odl/models/qatune10 LOG_odl/models/secondtune10 
python3 scripts/train_rl.py --env OpenDoorLoc --model secondtune10 --demos /home/ethantqiu/Thought-Cloning/demos/odl10 --memory-dim=1024 --recurrence=3 --batch-size=256 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 1e-6 --epochs 10 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 128 --expr-group-name LOG_odl --device 1 --wandb-id secondtune10 --target-update-period 1024
python3 scripts/train_rl.py --env OpenDoorLoc --model lang_scratch10 --demos /home/ethantqiu/Thought-Cloning/demos/odl10 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 1e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 128 --expr-group-name LOG_odl --device 1 --wandb-id lang_scratch10  --target-update-period 128 --language
python3 scripts/train_rl.py --env OpenDoorLoc --model scratch10 --demos /home/ethantqiu/Thought-Cloning/demos/odl10 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 1e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 128 --expr-group-name LOG_odl --device 1 --wandb-id scratch10  --target-update-period 128
    