python3 scripts/train_cql.py --env OpenDoorLoc --demos /home/yujustin/Desktop/Thought-Cloning/demos/odl0 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_odl_cql  --device 0 --wandb-id cql_odl_scratch --target-update-period 32
python3 scripts/train_iql.py --env OpenDoorLoc --demos /home/yujustin/Desktop/Thought-Cloning/demos/odl0 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_odl_iql  --device 0 --wandb-id iql_odl_scratch --target-update-period 32
python3 scripts/train_dqn.py --env OpenDoorLoc --demos /home/yujustin/Desktop/Thought-Cloning/demos/odl0 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_odl_dqn  --device 0 --wandb-id dqn_odl_scratch --target-update-period 32

python3 scripts/train_cql.py --env UnlockPickupDist --demos /home/yujustin/Desktop/Thought-Cloning/demos/upd0 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_upd_cql  --device 0 --wandb-id cql_upd_scratch --target-update-period 32
python3 scripts/train_iql.py --env UnlockPickupDist --demos /home/yujustin/Desktop/Thought-Cloning/demos/upd0 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_upd_iql  --device 0 --wandb-id iql_upd_scratch --target-update-period 32
python3 scripts/train_dqn.py --env UnlockPickupDist --demos /home/yujustin/Desktop/Thought-Cloning/demos/upd0 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_upd_dqn  --device 0 --wandb-id dqn_upd_scratch --target-update-period 32

python3 scripts/train_cql.py --env OpenDoorLoc --demos /home/yujustin/Desktop/Thought-Cloning/demos/odl10 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_odl_cql  --device 0 --wandb-id cql_odl_scratch_noisy10 --target-update-period 32
python3 scripts/train_iql.py --env OpenDoorLoc --demos /home/yujustin/Desktop/Thought-Cloning/demos/odl10 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_odl_iql  --device 0 --wandb-id iql_odl_scratch_noisy10 --target-update-period 32
python3 scripts/train_dqn.py --env OpenDoorLoc --demos /home/yujustin/Desktop/Thought-Cloning/demos/odl10 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_odl_dqn  --device 0 --wandb-id dqn_odl_scratch_noisy10 --target-update-period 32

python3 scripts/train_cql.py --env UnlockPickupDist --demos /home/yujustin/Desktop/Thought-Cloning/demos/upd10 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_upd_cql  --device 0 --wandb-id cql_upd_scratch_noisy10 --target-update-period 32
python3 scripts/train_iql.py --env UnlockPickupDist --demos /home/yujustin/Desktop/Thought-Cloning/demos/upd10 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_upd_iql  --device 0 --wandb-id iql_upd_scratch_noisy10 --target-update-period 32
python3 scripts/train_dqn.py --env UnlockPickupDist --demos /home/yujustin/Desktop/Thought-Cloning/demos/upd10 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_upd_dqn  --device 0 --wandb-id dqn_upd_scratch_noisy10 --target-update-period 32

python3 scripts/train_cql.py --env OpenDoorLoc --demos /home/yujustin/Desktop/Thought-Cloning/demos/odl0 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_odl_cql  --device 0 --wandb-id cql_odl_lower --target-update-period 32 --lower-only
python3 scripts/train_iql.py --env OpenDoorLoc --demos /home/yujustin/Desktop/Thought-Cloning/demos/odl0 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_odl_iql  --device 0 --wandb-id iql_odl_lower --target-update-period 32 --lower-only
python3 scripts/train_dqn.py --env OpenDoorLoc --demos /home/yujustin/Desktop/Thought-Cloning/demos/odl0 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_odl_dqn  --device 0 --wandb-id dqn_odl_lower --target-update-period 32 --lower-only

python3 scripts/train_cql.py --env UnlockPickupDist --demos /home/yujustin/Desktop/Thought-Cloning/demos/upd0 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_upd_cql  --device 0 --wandb-id cql_upd_lower --target-update-period 32 --lower-only
python3 scripts/train_iql.py --env UnlockPickupDist --demos /home/yujustin/Desktop/Thought-Cloning/demos/upd0 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_upd_iql  --device 0 --wandb-id iql_upd_lower --target-update-period 32 --lower-only
python3 scripts/train_dqn.py --env UnlockPickupDist --demos /home/yujustin/Desktop/Thought-Cloning/demos/upd0 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_upd_dqn  --device 0 --wandb-id dqn_upd_lower --target-update-period 32 --lower-only

python3 scripts/train_cql.py --env OpenDoorLoc --model /home/yujustin/Desktop/Thought-Cloning/LOG_ez_env/bc0/model --demos /home/yujustin/Desktop/Thought-Cloning/demos/odl0 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_odl_cql  --device 0 --wandb-id cql_odl_warmstart --target-update-period 32
python3 scripts/train_iql.py --env OpenDoorLoc --model /home/yujustin/Desktop/Thought-Cloning/LOG_ez_env/bc0/model --demos /home/yujustin/Desktop/Thought-Cloning/demos/odl0 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_odl_iql  --device 0 --wandb-id iql_odl_warmstart --target-update-period 32
python3 scripts/train_dqn.py --env OpenDoorLoc --model /home/yujustin/Desktop/Thought-Cloning/LOG_ez_env/bc0/model --demos /home/yujustin/Desktop/Thought-Cloning/demos/odl0 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_odl_dqn  --device 0 --wandb-id dqn_odl_warmstart --target-update-period 32

python3 scripts/train_cql.py --env UnlockPickupDist --model /home/yujustin/Desktop/Thought-Cloning/LOG_ez_env/bc0/model --demos /home/yujustin/Desktop/Thought-Cloning/demos/upd0 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_upd_cql  --device 0 --wandb-id cql_upd_warmstart --target-update-period 32
python3 scripts/train_iql.py --env UnlockPickupDist --model /home/yujustin/Desktop/Thought-Cloning/LOG_ez_env/bc0/model --demos /home/yujustin/Desktop/Thought-Cloning/demos/upd0 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_upd_iql  --device 0 --wandb-id iql_upd_warmstart --target-update-period 32
python3 scripts/train_dqn.py --env UnlockPickupDist --model /home/yujustin/Desktop/Thought-Cloning/LOG_ez_env/bc0/model --demos /home/yujustin/Desktop/Thought-Cloning/demos/upd0 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_upd_dqn  --device 0 --wandb-id dqn_upd_warmstart --target-update-period 32

python3 scripts/train_cql.py --env OpenDoorLoc --model /home/yujustin/Desktop/Thought-Cloning/LOG_ez_env/bc10/model --demos /home/yujustin/Desktop/Thought-Cloning/demos/odl10 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_odl_cql  --device 0 --wandb-id cql_odl_warmstart_noisy10 --target-update-period 32
python3 scripts/train_iql.py --env OpenDoorLoc --model /home/yujustin/Desktop/Thought-Cloning/LOG_ez_env/bc10/model --demos /home/yujustin/Desktop/Thought-Cloning/demos/odl10 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_odl_iql  --device 0 --wandb-id iql_odl_warmstart_noisy10 --target-update-period 32
python3 scripts/train_dqn.py --env OpenDoorLoc --model /home/yujustin/Desktop/Thought-Cloning/LOG_ez_env/bc10/model --demos /home/yujustin/Desktop/Thought-Cloning/demos/odl10 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_odl_dqn  --device 0 --wandb-id dqn_odl_warmstart_noisy10 --target-update-period 32

python3 scripts/train_cql.py --env UnlockPickupDist --model /home/yujustin/Desktop/Thought-Cloning/LOG_ez_env/bc10/model --demos /home/yujustin/Desktop/Thought-Cloning/demos/upd10 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_upd_cql  --device 0 --wandb-id cql_upd_warmstart_noisy10 --target-update-period 32
python3 scripts/train_iql.py --env UnlockPickupDist --model /home/yujustin/Desktop/Thought-Cloning/LOG_ez_env/bc10/model --demos /home/yujustin/Desktop/Thought-Cloning/demos/upd10 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_upd_iql  --device 0 --wandb-id iql_upd_warmstart_noisy10 --target-update-period 32
python3 scripts/train_dqn.py --env UnlockPickupDist --model /home/yujustin/Desktop/Thought-Cloning/LOG_ez_env/bc10/model --demos /home/yujustin/Desktop/Thought-Cloning/demos/upd10 --memory-dim=1024 --recurrence=3 --batch-size=128 --instr-arch=attgru --instr-dim=256 --val-interval 1 --log-interval 2 --lr 5e-4 --epochs 40 --epoch-length 10240 --seed 0 --val-seed 2023  --sg-coef 2 --tb --episodes 8192 --val-episodes 8 --expr-group-name LOG_upd_dqn  --device 0 --wandb-id dqn_upd_warmstart_noisy10 --target-update-period 32
